# Suppress warnings
import os, pathlib
from ai_shared_utilities import get_asset_path

os.environ["TF_XLA_FLAGS"] = "--tf_xla_auto_jit=0"
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping
import keras.ops as ops

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# Force CPU use for keras.
#os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
#os.environ["CUDA_VISIBLE_DEVICES"] = ""

DATA_ROOT = get_asset_path("aclImdb")
MODEL_PATH = (
    get_asset_path("full_transformer_encoder")
)

print("11.4.3 The Transformer encoder")
import tensorflow as tf
from tensorflow import keras

batch_size = 16
seed = 1337
val_split = 0.2  # 20% of train -> val

train_ds = keras.utils.text_dataset_from_directory(
    DATA_ROOT / "train",
    batch_size=batch_size,
    validation_split=val_split,
    subset="training",
    seed=seed,
)

val_ds = keras.utils.text_dataset_from_directory(
    DATA_ROOT / "train",
    batch_size=batch_size,
    validation_split=val_split,
    subset="validation",
    seed=seed,
)

test_ds = keras.utils.text_dataset_from_directory(
    DATA_ROOT / "test",
    batch_size=batch_size,
    shuffle=False,
)

text_only_train_ds = train_ds.map(lambda x, y: x)

print("Listing 11.12 Preparing integer sequence datasets")
from tensorflow.keras import layers

max_length = 600
max_tokens = 20000
text_vectorization = layers.TextVectorization(
        max_tokens=max_tokens,
        output_mode="int",
        # In order to keep a manageable input size, we'll truncate the inputs after the first 600 words.
        output_sequence_length=max_length,
)
text_vectorization.adapt(text_only_train_ds)

def peek_labels(ds, n=8):
    shown = 0
    for batch_x, batch_y in ds:
        bx = batch_x.numpy()
        by = batch_y.numpy()

        for i in range(len(by)):
            if shown >= n:
                return

            x_i = bx[i]
            y_i = by[i]

            if isinstance(x_i, (bytes, bytearray)):
                x_i = x_i.decode("utf-8", errors="replace")

            print("----")
            print("label:", int(y_i))
            print(x_i[:400])

            shown += 1    

peek_labels(test_ds, n=8)

int_train_ds = train_ds.map(
                lambda x, y: (text_vectorization(x), y),
                num_parallel_calls=tf.data.AUTOTUNE)
int_val_ds = val_ds.map(
                lambda x, y: (text_vectorization(x), y),
                num_parallel_calls=tf.data.AUTOTUNE)
int_test_ds = test_ds.map(
                lambda x, y: (text_vectorization(x), y),
                num_parallel_calls=tf.data.AUTOTUNE)

peek_labels(int_test_ds, n=8)
exit
print("Listing 11.21 Transformer encoder implemented as a subclassed Layer")
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        # Size of input token vectors
        self.embed_dim = embed_dim
        # Size of tthe inner dense layer
        self.dense_dim = dense_dim
        # Number of attention heads
        self.num_heads = num_heads
        self.attention = layers.MultiHeadAttention(
                num_heads=num_heads,
                key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
                [layers.Dense(dense_dim, activation="relu"),
                 layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    # Computation goes in call().
    def call(self, inputs, mask=None):
        # The mask that will be generated by tthe Embedding layer will be 2D,
        # but the attention layer expects to be 3D or 4D, so we expand its rank.
        if mask is not None:
            mask = mask[:, tf.newaxis, :]
        attention_output = self.attention(
                inputs,
                inputs,
                attention_mask=mask)
        proj_input = self.layernorm_1(inputs + attention_output)
        proj_output = self.dense_proj(proj_input)
        return self.layernorm_2(proj_input + proj_output)

    # Implement serialization so we can save the model.
    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

    def build(self, input_shape):
        # Let Keras know this layer is built.
        # Sublayers (attention, denseproj, layernorm) build themselves
        # automatically the first time they are called.
        super().build(input_shape)

print("Listing 11.24 Implementing positional embedding as a subclassed layer")

class PositionalEmbedding(layers.Layer):
    # A downside of position embeddings is that the sequence
    # length needs to be known in advance.
    def __init__(self, sequence_length, input_dim, output_dim, **kwargs):
        super().__init__(**kwargs)
        # Prepare an embedding layer for the token indices
        self.token_embeddings = layers.Embedding(
                input_dim=input_dim,
                output_dim=output_dim)
        self.position_embeddings = layers.Embedding(
                # And another one for the token positions.
                input_dim=sequence_length,
                output_dim=output_dim)
        self.sequence_length = sequence_length
        self.input_dim = input_dim
        self.output_dim = output_dim

    def call(self, inputs):
        length = tf.shape(inputs)[-1]
        positions = tf.range(start=0, limit=length, delta=1)
        embedded_tokens = self.token_embeddings(inputs)
        embedded_positions = self.position_embeddings(positions)
        return embedded_tokens + embedded_positions

    # Like the Embedding layer, this layer should be able to generate a mask so 
    # we can ignore padding zeros in the inputs. The compute_mask method will be 
    # called automatically by the framework, and the mask will get propogated 
    # to the next layer.
    def compute_mask(self, inputs, mask=None):
        return ops.not_equal(inputs, 0)

    # Implement serialization so we can save the model.
    def get_config(self):
        config = super().get_config()
        config.update({
            "output_dim": self.output_dim,
            "sequence_length": self.sequence_length,
            "input_dim": self.input_dim,
        })
        return config

    def build(self, input_shape):
        # Let Keras know this layer is built.
        # Sublayers (attention, denseproj, layernorm) build themselves
        # automatically the first time they are called.
        super().build(input_shape)

print("Listing 11.25 Combining the Transformer encoder with positional embedding")
vocab_size = 20000
sequence_length = 600
embed_dim = 256
num_heads = 2
dense_dim = 32

inputs = keras.Input(shape=(None,), dtype="int64")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(inputs)
x = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)
x = layers.GlobalMaxPooling1D()(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)
model.compile(optimizer="rmsprop",
        loss="binary_crossentropy",
        metrics=["accuracy"])
model.summary()

callbacks = [
        keras.callbacks.ModelCheckpoint(
        MODEL_PATH,
        save_best_only=True),
        EarlyStopping(monitor="val_loss",
                patience=3,
                restore_best_weights=True)
]
model.fit(int_train_ds,
        validation_data=int_val_ds,
        epochs=20,
        callbacks=callbacks)

import numpy as np
import tensorflow as tf

def show_mistakes(model, ds, n=20, binary=True, threshold=0.5):
    """
    Prints up to n misclassified examples from a tf.data.Dataset.
    Assumes ds yields (x, y) where x is either raw text (string) or token ids.
    If x is raw text, printing is nice. If x is token ids, you’ll see integers.
    """
    shown = 0

    for batch_x, batch_y in ds:
        # Predict on this batch
        preds = model(batch_x, training=False)

        # Normalize shapes to 1D arrays
        y_true = tf.reshape(batch_y, [-1]).numpy()

        if binary:
            # preds might be shape (B, 1) with sigmoid
            p = tf.reshape(preds, [-1]).numpy()
            y_pred = (p >= threshold).astype(np.int32)
        else:
            # preds shape (B, num_classes) with softmax (or logits)
            p = preds.numpy()
            y_pred = np.argmax(p, axis=-1).astype(np.int32)

        wrong_idx = np.where(y_pred != y_true)[0]
        if wrong_idx.size == 0:
            continue

        # Convert batch_x to something printable
        # If it's raw text, batch_x dtype is string -> decode bytes if needed.
        bx = batch_x.numpy() if hasattr(batch_x, "numpy") else batch_x

        for i in wrong_idx:
            if shown >= n:
                return

            x_i = bx[i]
            if isinstance(x_i, (bytes, np.bytes_)):
                x_i = x_i.decode("utf-8", errors="replace")

            if binary:
                print("----")
                print(f"true={int(y_true[i])} pred={int(y_pred[i])} p={float(p[i]):.4f}")
                print(x_i)
            else:
                # Show top probabilities (first few)
                top = np.argsort(-p[i])[:5]
                print("----")
                print(f"true={int(y_true[i])} pred={int(y_pred[i])} top5={[(int(k), float(p[i][k])) for k in top]}")
                print(x_i)

            shown += 1

# Wrap: string -> TextVectorization -> trained model
string_inputs = keras.Input(shape=(), dtype=tf.string, name="raw_text")
token_ids = text_vectorization(string_inputs)
outputs = model(token_ids)
debug_model = keras.Model(string_inputs, outputs, name="debug_model")

show_mistakes(debug_model, test_ds, n=25, binary=True)   # or binary=False for multi-class

model = keras.models.load_model(
        MODEL_PATH,
        custom_objects={"TransformerEncoder": TransformerEncoder,
                        "PositionalEmbedding": PositionalEmbedding})
print(f"Test acc: {model.evaluate(int_test_ds)[1]:.3f}")



